
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:584907642979:task-definition/flask-definition:2"
        LoadBalancerInfo:
          ContainerName: "flaskContainer"
          ContainerPort: 8080